export const MODEL_SOURCES = [
  {
    id: "openai-models",
    name: "OpenAI",
    homepage: "https://openai.com/newsroom",
    feedUrl: "https://openai.com/news/rss.xml",
    discoveryUrls: ["https://openai.com/newsroom", "https://openai.com/news"],
    articlePathPrefixes: ["/news/"],
    searchDomains: ["openai.com"],
    searchQueries: ["latest OpenAI model launch GPT Codex site:openai.com/news"],
    tags: ["openai", "models", "api"],
    keywords: ["gpt", "o1", "o3", "o4", "o5", "model", "api", "codex"],
  },
  {
    id: "anthropic-models",
    name: "Anthropic",
    homepage: "https://www.anthropic.com/news",
    feedUrl: "https://www.anthropic.com/news",
    discoveryUrls: ["https://www.anthropic.com/news"],
    format: "anthropic-newsroom",
    articlePathPrefixes: ["/news/"],
    searchDomains: ["anthropic.com"],
    searchQueries: ["latest Anthropic Claude model launch site:anthropic.com/news"],
    tags: ["anthropic", "claude", "models"],
    keywords: ["claude", "model", "api", "opus", "sonnet", "haiku"],
  },
  {
    id: "google-models",
    name: "Google DeepMind",
    homepage: "https://deepmind.google/blog",
    feedUrl: "https://deepmind.google/blog/rss.xml",
    discoveryUrls: ["https://deepmind.google/blog"],
    articlePathPrefixes: ["/blog/"],
    searchDomains: ["deepmind.google"],
    searchQueries: ["latest Google DeepMind Gemini Veo Imagen Gemma site:deepmind.google/blog"],
    tags: ["google", "deepmind", "gemini"],
    keywords: ["gemini", "veo", "imagen", "gemma", "lyria", "model"],
  },
  {
    id: "meta-models",
    name: "Meta AI",
    homepage: "https://about.fb.com/news/tag/ai/",
    feedUrl: "https://about.fb.com/news/tag/ai/feed/",
    discoveryUrls: ["https://about.fb.com/news/tag/ai/", "https://about.fb.com/news/"],
    articlePathPrefixes: ["/news/"],
    searchDomains: ["about.fb.com"],
    searchQueries: ["latest Meta AI Llama model launch site:about.fb.com/news"],
    tags: ["meta", "llama", "models"],
    keywords: ["llama", "ai model", "model", "muse", "sam"],
  },
  {
    id: "hugging-face-models",
    name: "Hugging Face",
    homepage: "https://huggingface.co/blog",
    feedUrl: "https://huggingface.co/blog/feed.xml",
    discoveryUrls: ["https://huggingface.co/blog"],
    articlePathPrefixes: ["/blog/"],
    searchDomains: ["huggingface.co"],
    searchQueries: ["latest Hugging Face models blog site:huggingface.co/blog"],
    tags: ["hugging-face", "open-source", "models"],
    keywords: ["model", "llm", "smol", "transformer", "embedding", "reranker", "vision"],
  },
];
