export const MODEL_SOURCES = [
  {
    id: "openai-models",
    name: "OpenAI",
    homepage: "https://openai.com/news",
    feedUrl: "https://openai.com/news/rss.xml",
    discoveryUrl: "https://openai.com/news",
    articlePathPrefixes: ["/news/"],
    tags: ["openai", "models", "api"],
    keywords: ["gpt", "o1", "o3", "o4", "model", "api"],
  },
  {
    id: "anthropic-models",
    name: "Anthropic",
    homepage: "https://www.anthropic.com/news",
    feedUrl: "https://www.anthropic.com/news",
    discoveryUrl: "https://www.anthropic.com/news",
    format: "anthropic-newsroom",
    articlePathPrefixes: ["/news/"],
    tags: ["anthropic", "claude", "models"],
    keywords: ["claude", "model", "api"],
  },
  {
    id: "google-models",
    name: "Google DeepMind",
    homepage: "https://deepmind.google/blog",
    feedUrl: "https://deepmind.google/blog/rss.xml",
    discoveryUrl: "https://deepmind.google/blog",
    articlePathPrefixes: ["/blog/"],
    tags: ["google", "deepmind", "gemini"],
    keywords: ["gemini", "veo", "imagen", "model"],
  },
  {
    id: "meta-models",
    name: "Meta AI",
    homepage: "https://about.fb.com/news/tag/ai/",
    feedUrl: "https://about.fb.com/news/tag/ai/feed/",
    discoveryUrl: "https://about.fb.com/news/tag/ai/",
    articlePathPrefixes: ["/news/"],
    tags: ["meta", "llama", "models"],
    keywords: ["llama", "ai model", "model"],
  },
  {
    id: "hugging-face-models",
    name: "Hugging Face",
    homepage: "https://huggingface.co/blog",
    feedUrl: "https://huggingface.co/blog/feed.xml",
    discoveryUrl: "https://huggingface.co/blog",
    articlePathPrefixes: ["/blog/"],
    tags: ["hugging-face", "open-source", "models"],
    keywords: ["model", "llm", "smol", "transformer"],
  },
];
