export const NEWS_SOURCES = [
  {
    id: "hugging-face",
    name: "Hugging Face",
    homepage: "https://huggingface.co/blog",
    feedUrl: "https://huggingface.co/blog/feed.xml",
    discoveryUrl: "https://huggingface.co/blog",
    articlePathPrefixes: ["/blog/"],
    tags: ["hugging-face", "models", "open-source"],
  },
  {
    id: "openai",
    name: "OpenAI",
    homepage: "https://openai.com/news",
    feedUrl: "https://openai.com/news/rss.xml",
    discoveryUrl: "https://openai.com/news",
    articlePathPrefixes: ["/news/"],
    tags: ["openai", "models", "api"],
  },
  {
    id: "anthropic",
    name: "Anthropic",
    homepage: "https://www.anthropic.com/news",
    feedUrl: "https://www.anthropic.com/news",
    discoveryUrl: "https://www.anthropic.com/news",
    format: "anthropic-newsroom",
    articlePathPrefixes: ["/news/"],
    tags: ["anthropic", "claude", "api"],
  },
  {
    id: "google-deepmind",
    name: "Google DeepMind",
    homepage: "https://deepmind.google/blog",
    feedUrl: "https://deepmind.google/blog/rss.xml",
    discoveryUrl: "https://deepmind.google/blog",
    articlePathPrefixes: ["/blog/"],
    tags: ["google", "deepmind", "gemini"],
  },
  {
    id: "meta-ai",
    name: "Meta AI",
    homepage: "https://about.fb.com/news/tag/ai/",
    feedUrl: "https://about.fb.com/news/tag/ai/feed/",
    discoveryUrl: "https://about.fb.com/news/tag/ai/",
    articlePathPrefixes: ["/news/"],
    tags: ["meta", "llama", "ai"],
  },
];
