export const NEWS_SOURCES = [
  {
    id: "hugging-face",
    name: "Hugging Face",
    homepage: "https://huggingface.co/blog",
    feedUrls: ["https://huggingface.co/blog/feed.xml"],
    discoveryUrls: ["https://huggingface.co/blog"],
    articlePathPrefixes: ["/blog/"],
    searchDomains: ["huggingface.co"],
    searchQueries: ["latest Hugging Face blog AI models site:huggingface.co/blog"],
    tags: ["hugging-face", "models", "open-source"],
  },
  {
    id: "openai",
    name: "OpenAI",
    homepage: "https://openai.com/newsroom",
    feedUrl: "https://openai.com/news/rss.xml",
    discoveryUrls: ["https://openai.com/newsroom", "https://openai.com/news"],
    articlePathPrefixes: ["/news/"],
    searchDomains: ["openai.com"],
    searchQueries: ["latest OpenAI newsroom product research site:openai.com/news"],
    tags: ["openai", "models", "api"],
  },
  {
    id: "anthropic",
    name: "Anthropic",
    homepage: "https://www.anthropic.com/news",
    feedUrl: "https://www.anthropic.com/news",
    discoveryUrls: ["https://www.anthropic.com/news"],
    format: "anthropic-newsroom",
    articlePathPrefixes: ["/news/"],
    searchDomains: ["anthropic.com"],
    searchQueries: ["latest Anthropic newsroom site:anthropic.com/news"],
    tags: ["anthropic", "claude", "api"],
  },
  {
    id: "google-deepmind",
    name: "Google DeepMind",
    homepage: "https://deepmind.google/blog",
    feedUrl: "https://deepmind.google/blog/rss.xml",
    discoveryUrls: ["https://deepmind.google/blog"],
    articlePathPrefixes: ["/blog/"],
    searchDomains: ["deepmind.google"],
    searchQueries: ["latest Google DeepMind blog AI models site:deepmind.google/blog"],
    tags: ["google", "deepmind", "gemini"],
  },
  {
    id: "meta-ai",
    name: "Meta AI",
    homepage: "https://about.fb.com/news/tag/ai/",
    feedUrl: "https://about.fb.com/news/tag/ai/feed/",
    discoveryUrls: ["https://about.fb.com/news/tag/ai/", "https://about.fb.com/news/"],
    articlePathPrefixes: ["/news/"],
    searchDomains: ["about.fb.com"],
    searchQueries: ["latest Meta AI newsroom site:about.fb.com/news"],
    tags: ["meta", "llama", "ai"],
  },
];
